services:
  jenkins:
    build: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_deploy_key:/var/jenkins_home/.ssh/id_ed25519:ro
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    restart: on-failure

  ngrok:
    image: ngrok/ngrok
    command:
      - "http"
      - "http://jenkins:8080"
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH}
    depends_on:
      - jenkins

volumes:
  jenkins_home: