pipeline {
    agent any

    environment {
        GITHUB_STATUS = 'success'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Set Permissions'){
            steps{
                script{
                    sh 'chmod +x ./employee-manager/mvnw'
                }
            }
        }

        stage('Build') {
            steps {
                dir('employee-manager') {
                    sh './mvnw clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('employee-manager') {
                    sh './mvnw test'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
