pipeline {
    agent any

    environment {
        GITHUB_STATUS = 'success'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                githubNotify context: 'CI Build', status: 'PENDING', description: 'Build is running...'
            }
        }

        stage('Set Permissions'){
            steps{
                script{
                    sh 'chmod +x ./employee-manager/mvnw'
                }
            }
        }

        stage('Build') {
            steps {
                dir('employee-manager') {
                    sh './mvnw clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('employee-manager') {
                    sh './mvnw test'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            script {
                githubNotify context: 'CI Build', status: 'SUCCESS', description: 'Build successful! 🎉'
            }
        }
        failure {
            script {
                githubNotify context: 'CI Build', status: 'FAILURE', description: 'Build failed ❌'
            }
        }
    }
}
